### ISSUE TITLE
Advertise PyPI version

### ISSUE THREAD

**Issue by jonas-eschle** [jiangyi15/tf-pwa#157]
I would suggest to put the PyPI version in the README in the front and make sure that this is up-to-date. Or is there anything wrong with the PyPI version and it should not be used? Also asking for a dependency

**Comment by jiangyi15** [comment]
The version in pypi is the stable version with tag, there is nothing wrong for it. Due to the too old version of the server we are using (ihep and lzuhep), it is would cause some problem when directly install from pypi. So, i do not add the pypi link. Fortunately, the servers have been updated recently. I can rewrite some parts of the README.

**Comment by jiangyi15** [comment]
I have updated the pypi version, the changelog is added in #159 .
